language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t paulg1878/docker-react -f Dockrfile.dev .

script:
    - docker run -e CI=true paulg1878/docker-react npm run test

